project_id: 756721  # Numeric project ID for levantetranslations
api_token: '161834fde81833a72996c125d9c1a1c801ae99ef15eb1d3889dfe9fbc55077aaea02b62f1e24278e'
base_path: '.'

files:
  - source: 'surveys/child_survey_translations.csv'
    translation: 'surveys/child_survey_translations.csv'
    first_line_contains_header: true
    scheme: 'identifier,labels,de,de_CH,source,es,es_AR,es_CO,fr,fr_CA,nl'
  - source: 'surveys/parent_survey_family_translations.csv'
    translation: 'surveys/parent_survey_family_translations.csv'
    first_line_contains_header: true
    scheme: 'identifier,labels,de,de_CH,source,es,es_AR,es_CO,fr,fr_CA,nl'
  - source: 'surveys/parent_survey_child_translations.csv'
    translation: 'surveys/parent_survey_child_translations.csv'
    first_line_contains_header: true
    scheme: 'identifier,labels,de,de_CH,source,es,es_AR,es_CO,fr,fr_CA,nl'
  - source: 'surveys/teacher_survey_general_translations.csv'
    translation: 'surveys/teacher_survey_general_translations.csv'
    first_line_contains_header: true
    scheme: 'identifier,labels,de,de_CH,source,es,es_AR,es_CO,fr,fr_CA,nl'
  - source: 'surveys/teacher_survey_classroom_translations.csv'
    translation: 'surveys/teacher_survey_classroom_translations.csv'
    first_line_contains_header: true
    scheme: 'identifier,labels,de,de_CH,source,es,es_AR,es_CO,fr,fr_CA,nl'
